apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: postgresql
spec:
  clusterIP: None  # This is what makes it headless!
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres