apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: mongodb
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb