apiVersion: batch/v1
kind: Job
metadata:
  name: python-auth-test-debug
  namespace: test-jobs
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          # Install required tools
          apk add --no-cache curl jq
          
          echo "=== Testing Python Auth Service ==="
          
          AUTH_SERVICE_URL="http://python-auth.microservices:8001"
          
          # Wait for service
          until curl -sf $AUTH_SERVICE_URL/health > /dev/null; do
            echo "Waiting for auth service..."
            sleep 2
          done
          
          echo "✓ Service is healthy"
          
          # Generate unique username
          UNIQUE_USER="testuser_$(date +%s)"
          TEST_PASSWORD="testpass123"
          
          # Test registration
          echo -e "\n1. Testing registration..."
          REGISTER_RESPONSE=$(curl -s -X POST $AUTH_SERVICE_URL/register \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"$UNIQUE_USER\",\"password\":\"$TEST_PASSWORD\",\"email\":\"$UNIQUE_USER@test.com\"}")
          
          echo "Registration response: $REGISTER_RESPONSE"
          
          # Test login
          echo -e "\n2. Testing login..."
          LOGIN_RESPONSE=$(curl -s -X POST $AUTH_SERVICE_URL/login \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"$UNIQUE_USER\",\"password\":\"$TEST_PASSWORD\"}")
          
          echo "Login response: $LOGIN_RESPONSE"
          
          # Extract token using jq (more reliable than grep)
          TOKEN=$(echo $LOGIN_RESPONSE | jq -r '.token')
          echo "Extracted token: $TOKEN"
          echo "Token length: ${#TOKEN}"
          
          # Test verify
          echo -e "\n3. Testing token verification..."
          VERIFY_RESPONSE=$(curl -s -X GET $AUTH_SERVICE_URL/verify \
            -H "Authorization: Bearer $TOKEN")
          
          echo "Verify response: $VERIFY_RESPONSE"
          
          # Also test with curl verbose to see headers
          echo -e "\n4. Verbose verification test..."
          curl -v -X GET $AUTH_SERVICE_URL/verify \
            -H "Authorization: Bearer $TOKEN"